"""create compliance_rules, maintenance_logs, mechanic_reports tables

Revision ID: 45eeaff37a5a
Revises: df8f4a5f72d8
Create Date: 2026-09-18 11:45:48.199578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45eeaff37a5a'
down_revision: Union[str, None] = 'df8f4a5f72d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_make', sa.String(length=100), nullable=False),
    sa.Column('vehicle_model', sa.String(length=100), nullable=False),
    sa.Column('service_type', sa.Enum('oil_change', 'brake_service', 'tire_rotation', 'engine_repair', 'transmission', 'electrical', 'body_work', 'general_inspection', 'other', name='service_type'), nullable=False),
    sa.Column('interval_km', sa.Integer(), nullable=False),
    sa.Column('interval_months', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_document', sa.String(length=500), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'vehicle_make', 'vehicle_model', 'service_type', name='uq_compliance_rule_org_make_model_type')
    )
    op.create_index(op.f('ix_compliance_rules_organization_id'), 'compliance_rules', ['organization_id'], unique=False)
    op.create_table('maintenance_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('odometer_at_service', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.Enum('oil_change', 'brake_service', 'tire_rotation', 'engine_repair', 'transmission', 'electrical', 'body_work', 'general_inspection', 'other', name='service_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mechanic_name', sa.String(length=255), nullable=True),
    sa.Column('next_due_km', sa.Integer(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_logs_organization_id'), 'maintenance_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_maintenance_logs_vehicle_id'), 'maintenance_logs', ['vehicle_id'], unique=False)
    op.create_table('mechanic_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('maintenance_log_id', sa.UUID(), nullable=False),
    sa.Column('diagnostic_notes', sa.Text(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('actions_taken', sa.Text(), nullable=True),
    sa.Column('parts_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['maintenance_log_id'], ['maintenance_logs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('maintenance_log_id')
    )
    op.create_index(op.f('ix_mechanic_reports_organization_id'), 'mechanic_reports', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mechanic_reports_organization_id'), table_name='mechanic_reports')
    op.drop_table('mechanic_reports')
    op.drop_index(op.f('ix_maintenance_logs_vehicle_id'), table_name='maintenance_logs')
    op.drop_index(op.f('ix_maintenance_logs_organization_id'), table_name='maintenance_logs')
    op.drop_table('maintenance_logs')
    op.drop_index(op.f('ix_compliance_rules_organization_id'), table_name='compliance_rules')
    op.drop_table('compliance_rules')
    # ### end Alembic commands ###

    # op.drop_table() does not drop the Postgres-native enum type it implicitly
    # created -- without this, re-running upgrade() after a downgrade fails with
    # "type already exists" (see e0ec432c0c0e for the same fix on Tier 2 enums).
    sa.Enum(name='service_type').drop(op.get_bind(), checkfirst=True)
