"""add agent session title

Revision ID: 55cad156abd5
Revises: 9c9934afdc67
Create Date: 2026-09-30 10:49:12.774936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55cad156abd5'
down_revision: Union[str, None] = '9c9934afdc67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_sessions', sa.Column('title', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_sessions', 'title')
    # ### end Alembic commands ###
