"""add_vehicle_assignments_table

Revision ID: b00dd9359ef1
Revises: ffbb489273d4
Create Date: 2026-09-18 13:26:13.006614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b00dd9359ef1'
down_revision: Union[str, None] = 'ffbb489273d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # vehicle_condition already exists (created by the driver_reports/
    # accountability migration) -- create_type=False so this table reuses it
    # instead of re-issuing CREATE TYPE, which op.create_table does NOT
    # checkfirst on its own. Plain sa.Enum silently ignores create_type; the
    # postgresql-dialect ENUM is required for it to take effect.
    vehicle_condition = postgresql.ENUM('good', 'fair', 'poor', name='vehicle_condition', create_type=False)
    op.create_table('vehicle_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_odometer', sa.Integer(), nullable=False),
    sa.Column('end_odometer', sa.Integer(), nullable=True),
    sa.Column('take_condition', vehicle_condition, nullable=False),
    sa.Column('leave_condition', vehicle_condition, nullable=True),
    sa.Column('take_notes', sa.Text(), nullable=True),
    sa.Column('leave_notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_assignments_driver_id'), 'vehicle_assignments', ['driver_id'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_organization_id'), 'vehicle_assignments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_vehicle_assignments_vehicle_id'), 'vehicle_assignments', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_assignments_vehicle_id'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_assignments_organization_id'), table_name='vehicle_assignments')
    op.drop_index(op.f('ix_vehicle_assignments_driver_id'), table_name='vehicle_assignments')
    op.drop_table('vehicle_assignments')
    # ### end Alembic commands ###
