"""expand_fleet_operational_fields

Revision ID: cfcd4366dc00
Revises: e5b2c9d4f6a8
Create Date: 2026-09-29 21:10:43.026886

Autogenerated, then hand-adjusted: enum types are created/dropped explicitly
(add_column does not emit CREATE TYPE), the new maintenance_log_services table
reuses the existing `service_type` enum, FKs are named, and existing rows are
backfilled (one service row per existing maintenance log; incident_time from
the incident's date; vehicles.added_by from created_by).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'cfcd4366dc00'
down_revision: Union[str, None] = 'e5b2c9d4f6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_SERVICE_TYPES = (
    'oil_change', 'brake_service', 'tire_rotation', 'engine_repair', 'transmission',
    'electrical', 'body_work', 'general_inspection', 'other',
)

service_scale = postgresql.ENUM('minor', 'major', name='service_scale', create_type=False)
supplier_category = postgresql.ENUM(
    'workshop', 'tire_supplier', 'parts_supplier', 'fuel_station', 'other', name='supplier_category', create_type=False
)
vehicle_ownership_type = postgresql.ENUM('leasing', 'rent', 'owner', name='vehicle_ownership_type', create_type=False)
# Already exists (created with compliance_rules/maintenance_logs) -- reference only.
existing_service_type = postgresql.ENUM(*_SERVICE_TYPES, name='service_type', create_type=False)


def upgrade() -> None:
    bind = op.get_bind()
    service_scale.create(bind, checkfirst=True)
    supplier_category.create(bind, checkfirst=True)
    vehicle_ownership_type.create(bind, checkfirst=True)

    # --- Foundation -----------------------------------------------------------
    op.add_column('vehicles', sa.Column('engine_number', sa.String(length=100), nullable=True))
    op.add_column('vehicles', sa.Column('chassis_number', sa.String(length=100), nullable=True))
    op.add_column('vehicles', sa.Column('ownership_type', vehicle_ownership_type, server_default='owner', nullable=False))
    op.add_column('vehicles', sa.Column('added_by', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_vehicles_added_by_users', 'vehicles', 'users', ['added_by'], ['id'])
    # Existing rows: the record's creator is the best available attribution.
    op.execute("UPDATE vehicles SET added_by = created_by WHERE added_by IS NULL")

    op.add_column('drivers', sa.Column('license_type', sa.String(length=100), nullable=True))
    op.add_column('drivers', sa.Column('license_issue_date', sa.Date(), nullable=True))
    op.add_column('drivers', sa.Column('license_current_status', sa.String(length=50), nullable=True))

    op.add_column('suppliers', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('suppliers', sa.Column('category', supplier_category, server_default='other', nullable=False))

    # --- Fuel -----------------------------------------------------------------
    op.add_column('fuel_logs', sa.Column('po_number', sa.String(length=100), nullable=True))
    op.add_column('fuel_logs', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('fuel_logs', sa.Column('card_used', sa.String(length=100), nullable=True))
    op.add_column('fuel_logs', sa.Column('fuel_station_name', sa.String(length=255), nullable=True))
    op.add_column('fuel_logs', sa.Column('slip_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_fuel_logs_slip_id'), 'fuel_logs', ['slip_id'], unique=False)

    # --- Accountability (incidents) --------------------------------------------
    op.add_column('incident_logs', sa.Column('incident_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incident_logs', sa.Column('location_area', sa.String(length=255), nullable=True))
    op.add_column('incident_logs', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('incident_logs', sa.Column('attachment_url', sa.String(length=1000), nullable=True))
    op.execute("UPDATE incident_logs SET incident_time = date::timestamptz WHERE incident_time IS NULL")

    # --- Maintenance ------------------------------------------------------------
    op.add_column('maintenance_logs', sa.Column('service_scale', service_scale, server_default='minor', nullable=False))
    op.add_column('maintenance_logs', sa.Column('driver_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_maintenance_logs_driver_id'), 'maintenance_logs', ['driver_id'], unique=False)
    op.create_foreign_key('fk_maintenance_logs_driver_id_drivers', 'maintenance_logs', 'drivers', ['driver_id'], ['id'])

    op.create_table(
        'maintenance_log_services',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('maintenance_log_id', sa.UUID(), nullable=False),
        sa.Column('service_type', existing_service_type, nullable=False),
        sa.Column('position', sa.Integer(), server_default='0', nullable=False),
        sa.ForeignKeyConstraint(['maintenance_log_id'], ['maintenance_logs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('maintenance_log_id', 'service_type', name='uq_maintenance_log_service'),
    )
    op.create_index(
        op.f('ix_maintenance_log_services_maintenance_log_id'), 'maintenance_log_services', ['maintenance_log_id'], unique=False
    )
    op.create_index(
        op.f('ix_maintenance_log_services_service_type'), 'maintenance_log_services', ['service_type'], unique=False
    )
    # Every pre-existing maintenance log had exactly one service_type.
    op.execute(
        "INSERT INTO maintenance_log_services (id, maintenance_log_id, service_type, position) "
        "SELECT gen_random_uuid(), id, service_type, 0 FROM maintenance_logs"
    )


def downgrade() -> None:
    op.drop_index(op.f('ix_maintenance_log_services_service_type'), table_name='maintenance_log_services')
    op.drop_index(op.f('ix_maintenance_log_services_maintenance_log_id'), table_name='maintenance_log_services')
    op.drop_table('maintenance_log_services')

    op.drop_constraint('fk_maintenance_logs_driver_id_drivers', 'maintenance_logs', type_='foreignkey')
    op.drop_index(op.f('ix_maintenance_logs_driver_id'), table_name='maintenance_logs')
    op.drop_column('maintenance_logs', 'driver_id')
    op.drop_column('maintenance_logs', 'service_scale')

    op.drop_column('incident_logs', 'attachment_url')
    op.drop_column('incident_logs', 'remarks')
    op.drop_column('incident_logs', 'location_area')
    op.drop_column('incident_logs', 'incident_time')

    op.drop_index(op.f('ix_fuel_logs_slip_id'), table_name='fuel_logs')
    op.drop_column('fuel_logs', 'slip_id')
    op.drop_column('fuel_logs', 'fuel_station_name')
    op.drop_column('fuel_logs', 'card_used')
    op.drop_column('fuel_logs', 'payment_method')
    op.drop_column('fuel_logs', 'po_number')

    op.drop_column('suppliers', 'category')
    op.drop_column('suppliers', 'address')

    op.drop_column('drivers', 'license_current_status')
    op.drop_column('drivers', 'license_issue_date')
    op.drop_column('drivers', 'license_type')

    op.drop_constraint('fk_vehicles_added_by_users', 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'added_by')
    op.drop_column('vehicles', 'ownership_type')
    op.drop_column('vehicles', 'chassis_number')
    op.drop_column('vehicles', 'engine_number')

    bind = op.get_bind()
    vehicle_ownership_type.drop(bind, checkfirst=True)
    supplier_category.drop(bind, checkfirst=True)
    service_scale.drop(bind, checkfirst=True)
