"""create trip_logs, driver_reports, incident_logs tables

Revision ID: ffbb489273d4
Revises: 45eeaff37a5a
Create Date: 2026-09-18 12:18:07.007474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffbb489273d4'
down_revision: Union[str, None] = '45eeaff37a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('vehicle_condition', sa.Enum('good', 'fair', 'poor', name='vehicle_condition'), nullable=False),
    sa.Column('handover_notes', sa.Text(), nullable=True),
    sa.Column('issues_reported', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_reports_driver_id'), 'driver_reports', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_reports_organization_id'), 'driver_reports', ['organization_id'], unique=False)
    op.create_index(op.f('ix_driver_reports_vehicle_id'), 'driver_reports', ['vehicle_id'], unique=False)
    op.create_table('incident_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('incident_type', sa.Enum('damage', 'violation', 'near_miss', name='incident_type'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('severity', sa.Enum('minor', 'moderate', 'severe', 'critical', name='incident_severity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location_description', sa.Text(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('resolution_status', sa.Enum('open', 'investigating', 'resolved', 'closed', name='incident_resolution_status'), server_default='open', nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_logs_organization_id'), 'incident_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_incident_logs_vehicle_id'), 'incident_logs', ['vehicle_id'], unique=False)
    op.create_table('trip_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_odometer', sa.Integer(), nullable=False),
    sa.Column('end_odometer', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Integer(), nullable=False),
    sa.Column('fuel_consumed', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_logs_driver_id'), 'trip_logs', ['driver_id'], unique=False)
    op.create_index(op.f('ix_trip_logs_organization_id'), 'trip_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_trip_logs_vehicle_id'), 'trip_logs', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_logs_vehicle_id'), table_name='trip_logs')
    op.drop_index(op.f('ix_trip_logs_organization_id'), table_name='trip_logs')
    op.drop_index(op.f('ix_trip_logs_driver_id'), table_name='trip_logs')
    op.drop_table('trip_logs')
    op.drop_index(op.f('ix_incident_logs_vehicle_id'), table_name='incident_logs')
    op.drop_index(op.f('ix_incident_logs_organization_id'), table_name='incident_logs')
    op.drop_table('incident_logs')
    op.drop_index(op.f('ix_driver_reports_vehicle_id'), table_name='driver_reports')
    op.drop_index(op.f('ix_driver_reports_organization_id'), table_name='driver_reports')
    op.drop_index(op.f('ix_driver_reports_driver_id'), table_name='driver_reports')
    op.drop_table('driver_reports')
    # ### end Alembic commands ###

    # op.drop_table() does not drop the Postgres-native enum types it
    # implicitly created -- without this, re-running upgrade() after a
    # downgrade fails with "type already exists" (see e0ec432c0c0e for the
    # same fix on Tier 2 enums).
    sa.Enum(name='incident_resolution_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='incident_severity').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='incident_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='vehicle_condition').drop(op.get_bind(), checkfirst=True)
